django_pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
"""Defines URL patterns for pizzas"""
from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    #Home Page
    path('', views.index, name='index'),
    #Page that shows all pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    #Detail page for a single pizza
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzas/models.py
"""import models from django db"""
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """The types of pizzas that exist"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return str(self.name)

class Topping(models.Model):
    """Specific toppings on the type of pizza"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE, )
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) < 25:
            return f"{self.text}"
        else:
            return f"{self.text[:25]}..."

pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for my django pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas"""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and its toppings"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a  href="{% url 'pizzas:index' %}">Django Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Django Pizzeria</p>

<p>Welcome to the Django Pizzeria, feel free to order any pizzas out for delivery</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza type: {{ pizza }}</p>
<ul>
    {% for topping in toppings %}
        <li>
            <p>{{ topping.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no toppings listed for this pizza</li>
    {% endfor %}
</ul>
{% endblock content%}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
        <li><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></li>
    {% empty %}
        <li>No pizzas have been added</li>
    {% endfor %}
</ul>
{% endblock content%}